name: OinkBI
main: com.github.oinkcraft.oinkbi.Main
version: '1.0'
depend:
  - Essentials

commands:
  oinkbi:
    description: A command to opt out or opt int.
    usage: /<command> [optout|optin]